# =======================================================================
#   ██╗  ██╗███████╗███╗   ██╗██████╗ ███████╗██╗      █████╗ ██╗   ██╗
#   ╚██╗██╔╝██╔════╝████╗  ██║██╔══██╗██╔════╝██║     ██╔══██╗╚██╗ ██╔╝
#    ╚███╔╝ █████╗  ██╔██╗ ██║██║  ██║█████╗  ██║     ███████║ ╚████╔╝
#    ██╔██╗ ██╔══╝  ██║╚██╗██║██║  ██║██╔══╝  ██║     ██╔══██║  ╚██╔╝
#   ██╔╝ ██╗███████╗██║ ╚████║██████╔╝███████╗███████╗██║  ██║   ██║
#   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝
# =======================================================================
# Plugin by XenVision & okunivaxx (TGK: @xen_vision)
# Config for XenDelay
# ----------------------------------------------------------------------
settings:
  locate: ru  # Возможные значения: "ru", "en", "fr"
lag_settings:
  lag_intensity: 0.3  # Как сильно телепортировать игрока (0.1 = слабые лаги, 1.0 = мощные)
  lag_frequency: 20   # Как часто происходит лаг (20 тиков = 1 раз в секунду)
  lag_duration: -1    # Длительность лагов в секундах (-1 = бесконечно)
  lag_message_chance: 0.7  # Вероятность получить сообщение о лаге (0.0 = никогда, 1.0 = всегда)
  enable_lag_messages: true # Включить/выключить сообщения о потерях пакетов