name: XenDelay
version: '2.0.0'
main: net.xenvision.xendelay.XenDelay
api-version: '1.16'
authors: [XenVision]
commands:
  xendelay:
    description: Управление лагами игроков (/xendelay help)
    usage: /xendelay <lag|unlag|unlagall|reload|language>
    permission: xendelay.use
permissions:
  xendelay.use:
    default: op
  xendelay.lag:
    default: op
  xendelay.unlag:
    default: op
  xendelay.reload:
    default: op
  xendelay.language:
    default: op
  xendelay.unlagall:
    default: op
  xendelay.gui:
    default: op